version: '3'

tasks:
  serve:
    desc: Start Hugo development server
    cmd: hugo server --buildDrafts

  build:
    desc: Build the Hugo site
    cmd: hugo --buildDrafts

  test:
    desc: Test site rendering
    cmd: hugo --buildDrafts --destination /tmp/hugo-test

  clean:
    desc: Clean generated files
    cmd: rm -rf public/ resources/