version: '3'

tasks:
  install-docs:
    desc: Install Docusaurus dependencies
    dir: docusaurus
    cmds:
      - npm install

  build-docs:
    desc: Build Docusaurus documentation
    dir: docusaurus
    deps: [install-docs]
    cmds:
      - npm run build

  build-hugo:
    desc: Build Hugo site
    cmds:
      - hugo --buildDrafts

  build:
    desc: Build complete site with docs
    cmds:
      - task: build-hugo
      - task: build-docs
      - cp -r docusaurus/build/* public/
      - echo "Build complete. Docs available at:"
      - echo "- /konductor/docs/"
      - echo "- /pvc-chonker/docs/"
      - echo "- /secret-santa/docs/"

  serve-docs:
    desc: Serve Docusaurus in development
    dir: docusaurus
    deps: [install-docs]
    cmds:
      - npm run start

  serve:
    desc: Start Hugo development server
    cmd: hugo server --buildDrafts

  test:
    desc: Test site rendering
    cmd: hugo --buildDrafts --destination /tmp/hugo-test

  clean:
    desc: Clean generated files
    cmds:
      - rm -rf public/ resources/
      - rm -rf docusaurus/build/
      - rm -rf docusaurus/node_modules/