version: '3'

tasks:
  install-docs:
    desc: Install Docusaurus dependencies
    dir: docusaurus
    cmds:
      - npm install

  build-docs:
    desc: Build Docusaurus documentation
    dir: docusaurus
    deps: [install-docs]
    cmds:
      - npm run build

  build-hugo:
    desc: Build Hugo site
    cmds:
      - hugo --buildDrafts

  build:
    desc: Build complete site with docs
    cmds:
      - task: build-hugo
      - task: build-docs
      - cp -r docusaurus/build/* public/
      - echo "Generating combined sitemap index..."
      - |
        cat > public/sitemap-index.xml << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
          <sitemap>
            <loc>https://logiciq.ca/sitemap.xml</loc>
            <lastmod>$(date -u +"%Y-%m-%dT%H:%M:%SZ")</lastmod>
          </sitemap>
          <sitemap>
            <loc>https://logiciq.ca/docs/sitemap.xml</loc>
            <lastmod>$(date -u +"%Y-%m-%dT%H:%M:%SZ")</lastmod>
          </sitemap>
        </sitemapindex>
        EOF
      - echo "Build complete. Docs available at:"
      - echo "- /docs/konductor/"
      - echo "- /docs/pvc-chonker/"
      - echo "- /docs/secret-santa/"
      - echo "Sitemaps available at:"
      - echo "- /sitemap.xml (Hugo main site)"
      - echo "- /docs/sitemap.xml (Docusaurus docs)"
      - echo "- /sitemap-index.xml (Combined index)"

  serve-docs:
    desc: Serve Docusaurus in development
    dir: docusaurus
    deps: [install-docs]
    cmds:
      - npm run start

  serve:
    desc: Start Hugo development server
    cmd: hugo server --buildDrafts

  test:
    desc: Test site rendering
    cmd: hugo --buildDrafts --destination /tmp/hugo-test

  clean:
    desc: Clean generated files
    cmds:
      - rm -rf public/ resources/
      - rm -rf docusaurus/build/
      - rm -rf docusaurus/node_modules/